"""Real-time DHCP lease events via dnsmasq's `dhcp-script` hook.

dnsmasq runs the hook on every lease add / renew (`old`) / expiry (`del`).
The rendered hook (RENDER_DIR/lease-event.sh, generated by dnsmasq.py) is a
few lines of bash that write "<action> <mac> <ip> <hostname>" to
127.0.0.1:EVENT_PORT over UDP — no privileges, no filesystem, no python
start-up per lease. This module listens there.

Trust model: the datagram is a TRIGGER, not a source of truth. Anything on
the host can send one, so an event is only accepted when the leases file
agrees (add/old: that MAC holds that IP; del: it no longer does), and what
it triggers — an immediate new-device alert, an instant refresh for open
lease tables — is something a spoofer could at worst cause early.
"""
import os
import time
import socket
import threading
from collections import deque
from flask import Blueprint, jsonify

from .core.store import load_store
from .core.validators import RE_HOSTNAME, RE_MAC, is_ipv4
from .dhcp import parse_leases

bp = Blueprint('events', __name__)

EVENT_PORT = int(os.environ.get('DNSMAQ_EVENT_PORT', 8453))
ACTIONS = ('add', 'old', 'del')

_recent = deque(maxlen=200)
_lock = threading.Lock()
_started = False
_last_ts = 0


def parse_event(text):
    """'<action> <mac> <ip> [hostname]' → dict, or None when malformed."""
    parts = (text or '').strip().split()
    if len(parts) < 3 or parts[0] not in ACTIONS:
        return None
    mac, ip = parts[1].lower(), parts[2]
    if not RE_MAC.match(mac) or not is_ipv4(ip):
        return None
    host = parts[3] if len(parts) > 3 and RE_HOSTNAME.match(parts[3]) else ''
    return {'action': parts[0], 'mac': mac, 'ip': ip, 'hostname': host}


def corroborated(ev, leases=None):
    """The leases file is the source of truth; the datagram only says look."""
    leases = parse_leases() if leases is None else leases
    held = {(l['mac'].lower(), l['ip']) for l in leases}
    if ev['action'] == 'del':
        return (ev['mac'], ev['ip']) not in held
    return (ev['mac'], ev['ip']) in held


def handle(text):
    """Validate one datagram and act on it. Returns the accepted event or None."""
    global _last_ts
    ev = parse_event(text)
    if not ev:
        return None
    # dnsmasq rewrites the leases file just before running the hook, but give
    # a slow disk a moment before deciding the event lied.
    ok = corroborated(ev)
    if not ok:
        time.sleep(0.2)
        ok = corroborated(ev)
    if not ok:
        return None
    from . import oui
    ev.update({'ts': int(time.time()), 'vendor': oui.vendor(ev['mac'])})
    with _lock:
        _recent.append(ev)
        _last_ts = ev['ts']
    if ev['action'] == 'add':
        try:
            from . import alerts
            alerts.lease_event(ev)
        except Exception as e:
            print('lease event alert failed: %s' % e, flush=True)
    return ev


def _serve(sock):
    while True:
        try:
            data, _ = sock.recvfrom(512)
        except OSError:
            return
        try:
            handle(data.decode('utf-8', errors='replace'))
        except Exception as e:
            print('lease event handling failed: %s' % e, flush=True)


def start_listener():
    """Bind the loopback UDP listener once (called from app.py at boot)."""
    global _started
    if _started:
        return True
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        sock.bind(('127.0.0.1', EVENT_PORT))
    except OSError as e:
        print('lease events: cannot listen on 127.0.0.1:%d (%s) — hook disabled'
              % (EVENT_PORT, e), flush=True)
        return False
    _started = True
    threading.Thread(target=_serve, args=(sock,), daemon=True).start()
    return True


def hook_script():
    """The dhcp-script dnsmasq runs; rendered into RENDER_DIR by dnsmasq.py.
    bash's /dev/udp does the send, so there is nothing to install."""
    return ('#!/bin/bash\n'
            '# Managed by DNSMAQ-MGR — dnsmasq dhcp-script hook: report lease\n'
            '# events to the app over loopback UDP. Regenerated on every apply.\n'
            'exec 3>/dev/udp/127.0.0.1/%d 2>/dev/null || exit 0\n'
            'printf \'%%s %%s %%s %%s\\n\' "$1" "$2" "$3" "${4:-}" >&3\n'
            'exec 3>&-\n' % EVENT_PORT)


@bp.route('/api/dhcp/events')
def events_get():
    settings = load_store('settings')
    with _lock:
        items = list(_recent)[-100:][::-1]
        last = _last_ts
    return jsonify({'success': True, 'listening': _started, 'port': EVENT_PORT,
                    'enabled': bool(settings.get('lease_events', True)),
                    'active': bool(settings.get('dhcp_enabled') and settings.get('lease_events', True)),
                    'last_ts': last, 'events': items})
